version: '2'

services:
    kibana:
        image: kibana
        ports:
            - "5601:5601"
        links:
          - elasticsearch

    elasticsearch:
        image: elasticsearch
        ports:
            - "9200:9200"
